# Embed a binary file as a C byte array TU. Usage:
#   cmake -DIN=<file> -DOUT=<generated.cpp> -DSYMBOL=<identifier> -P EmbedBinary.cmake
# Emits: const unsigned char <SYMBOL>[]; const unsigned long long <SYMBOL>Size;
file(READ "${IN}" _hex HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
file(WRITE "${OUT}" "// Generated by EmbedBinary.cmake from ${IN} - do not edit.\n")
file(APPEND "${OUT}" "extern const unsigned char ${SYMBOL}[];\n")
file(APPEND "${OUT}" "extern const unsigned long long ${SYMBOL}Size;\n")
file(APPEND "${OUT}" "const unsigned char ${SYMBOL}[] = {${_bytes}};\n")
file(APPEND "${OUT}" "const unsigned long long ${SYMBOL}Size = sizeof(${SYMBOL});\n")
