# Script mode (cmake -P): generate BuildStamp.cpp - the identity a running binary logs at
# startup so a build can be told apart from a stale/cached one (browsers cache .wasm HARD;
# the stamp is the ground truth for "am I running what I just built").
#
# Content: <git short hash>[-dirty.<fp8>] @ <generation time>. fp8 = a fingerprint over the
# MODIFIED tracked files (path + mtime + size), so the stamp changes EXACTLY when source
# changed - iterating a dirty tree refreshes it per edit, while true no-op rebuilds keep
# the file byte-identical and nothing relinks.
#
# Inputs: -DOUT=<path to BuildStamp.cpp> -DSRC_ROOT=<repo root>

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY "${SRC_ROOT}"
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE GIT_RESULT)
if(NOT GIT_RESULT EQUAL 0)
    set(GIT_HASH "nogit")
endif()

execute_process(
    COMMAND git status --porcelain --untracked-files=no
    WORKING_DIRECTORY "${SRC_ROOT}"
    OUTPUT_VARIABLE GIT_STATUS
    ERROR_QUIET)

set(SUFFIX "")
if(NOT "${GIT_STATUS}" STREQUAL "")
    # Fingerprint the modified set: path + mtime + size per entry.
    string(REPLACE "\n" ";" STATUS_LINES "${GIT_STATUS}")
    set(FP_INPUT "")
    foreach(LINE ${STATUS_LINES})
        string(LENGTH "${LINE}" LINE_LEN)
        if(LINE_LEN GREATER 3)
            string(SUBSTRING "${LINE}" 3 -1 REL_PATH)
            set(ABS_PATH "${SRC_ROOT}/${REL_PATH}")
            set(MTIME "gone")
            set(SIZE "0")
            if(EXISTS "${ABS_PATH}")
                file(TIMESTAMP "${ABS_PATH}" MTIME "%Y%m%d%H%M%S")
                file(SIZE "${ABS_PATH}" SIZE)
            endif()
            string(APPEND FP_INPUT "${REL_PATH}:${MTIME}:${SIZE};")
        endif()
    endforeach()
    string(MD5 FP "${FP_INPUT}")
    string(SUBSTRING "${FP}" 0 8 FP8)
    set(SUFFIX "-dirty.${FP8}")
endif()

string(TIMESTAMP STAMP_TIME "%Y-%m-%d %H:%M")

set(CONTENT "// GENERATED by GenerateBuildStamp.cmake - do not edit, do not commit.
extern \"C\" const char* DraconicBuildStamp()
{
    return \"${GIT_HASH}${SUFFIX} @ ${STAMP_TIME}\";
}
")

# Write only on change: the timestamp refreshes only alongside a hash/fingerprint change,
# so an unchanged tree keeps the file byte-identical and no-op builds stay no-op.
set(EXISTING "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" EXISTING)
endif()
string(FIND "${EXISTING}" "${GIT_HASH}${SUFFIX} @" SAME_IDENTITY)
if(SAME_IDENTITY EQUAL -1)
    file(WRITE "${OUT}" "${CONTENT}")
endif()
